#ifndef COMP_BP_METRIC_SUMMARY_CARD_H
#define COMP_BP_METRIC_SUMMARY_CARD_H

#include "comp_user_card.h"

#include <stdint.h>

#include "lvgl.h"
#include "health_ui_display_policy.h"
#include "../../layout/layout_fonts.h"

#ifndef COMP_BP_SUMMARY_CARD_RADIUS_PX
#define COMP_BP_SUMMARY_CARD_RADIUS_PX (14)
#endif

#ifndef COMP_BP_SUMMARY_CARD_BG_COLOR_HEX
#define COMP_BP_SUMMARY_CARD_BG_COLOR_HEX (0xE7E8EB)
#endif

#ifndef COMP_BP_SUMMARY_CARD_BG_WARNING_COLOR_HEX
#define COMP_BP_SUMMARY_CARD_BG_WARNING_COLOR_HEX (0xFDF8E5)
#endif

#ifndef COMP_BP_SUMMARY_CARD_BG_CRITICAL_COLOR_HEX
#define COMP_BP_SUMMARY_CARD_BG_CRITICAL_COLOR_HEX (0xFFF1F1)
#endif

#ifndef COMP_BP_SUMMARY_CARD_BORDER_WARNING_COLOR_HEX
#define COMP_BP_SUMMARY_CARD_BORDER_WARNING_COLOR_HEX (0xF2CF66)
#endif

#ifndef COMP_BP_SUMMARY_CARD_BORDER_CRITICAL_COLOR_HEX
#define COMP_BP_SUMMARY_CARD_BORDER_CRITICAL_COLOR_HEX (0xF59AA0)
#endif

#ifndef COMP_BP_SUMMARY_CARD_BORDER_WIDTH_PX
#define COMP_BP_SUMMARY_CARD_BORDER_WIDTH_PX (1)
#endif

#ifndef COMP_BP_SUMMARY_CARD_PAD_PX
#define COMP_BP_SUMMARY_CARD_PAD_PX (10)
#endif

#ifndef COMP_BP_SUMMARY_CARD_ROW_GAP_PX
#define COMP_BP_SUMMARY_CARD_ROW_GAP_PX HL_SCALE_V(6)
#endif

#ifndef COMP_BP_SUMMARY_CARD_DOT_SIZE_PX
#define COMP_BP_SUMMARY_CARD_DOT_SIZE_PX (10)
#endif

#ifndef COMP_BP_SUMMARY_CARD_METRIC_FONT
#define COMP_BP_SUMMARY_CARD_METRIC_FONT HL_FONT_TITLE
#endif

#ifndef COMP_BP_SUMMARY_CARD_VALUE_FONT
#define COMP_BP_SUMMARY_CARD_VALUE_FONT HL_FONT_HERO
#endif

#ifndef COMP_BP_SUMMARY_CARD_UNIT_FONT
#define COMP_BP_SUMMARY_CARD_UNIT_FONT HL_FONT_CAPTION
#endif

#ifndef COMP_BP_SUMMARY_CARD_STATUS_FONT
#define COMP_BP_SUMMARY_CARD_STATUS_FONT HL_FONT_CAPTION
#endif

#ifndef COMP_BP_SUMMARY_CARD_LABEL_COLOR_HEX
#define COMP_BP_SUMMARY_CARD_LABEL_COLOR_HEX (0x222222)
#endif

#ifndef COMP_BP_SUMMARY_CARD_VALUE_COLOR_HEX
#define COMP_BP_SUMMARY_CARD_VALUE_COLOR_HEX (0x1D2024)
#endif

#ifndef COMP_BP_SUMMARY_CARD_UNIT_COLOR_HEX
#define COMP_BP_SUMMARY_CARD_UNIT_COLOR_HEX (0x7E8793)
#endif

#ifndef COMP_BP_SUMMARY_CARD_STATUS_NORMAL_BG_HEX
#define COMP_BP_SUMMARY_CARD_STATUS_NORMAL_BG_HEX (0xFFFFFF)
#endif

#ifndef COMP_BP_SUMMARY_CARD_STATUS_NORMAL_TEXT_HEX
#define COMP_BP_SUMMARY_CARD_STATUS_NORMAL_TEXT_HEX (0x8A94A2)
#endif

#ifndef COMP_BP_SUMMARY_CARD_STATUS_WARNING_BG_HEX
#define COMP_BP_SUMMARY_CARD_STATUS_WARNING_BG_HEX (0xF8E8AF)
#endif

#ifndef COMP_BP_SUMMARY_CARD_STATUS_WARNING_TEXT_HEX
#define COMP_BP_SUMMARY_CARD_STATUS_WARNING_TEXT_HEX (0x8A5A00)
#endif

#ifndef COMP_BP_SUMMARY_CARD_STATUS_CRITICAL_BG_HEX
#define COMP_BP_SUMMARY_CARD_STATUS_CRITICAL_BG_HEX (0xF3B8B4)
#endif

#ifndef COMP_BP_SUMMARY_CARD_STATUS_CRITICAL_TEXT_HEX
#define COMP_BP_SUMMARY_CARD_STATUS_CRITICAL_TEXT_HEX (0xB42318)
#endif

#ifndef COMP_BP_SUMMARY_CARD_STATUS_HEIGHT_PX
#define COMP_BP_SUMMARY_CARD_STATUS_HEIGHT_PX HL_SCALE_V(24)
#endif

#ifndef COMP_BP_SUMMARY_CARD_STATUS_RADIUS_PX
#define COMP_BP_SUMMARY_CARD_STATUS_RADIUS_PX (12)
#endif

typedef struct {
  const char *label_text;
  const char *unit_text;
  const char *value_text;
  const char *status_text;
  comp_user_status_level_t status_level;
  uint32_t accent_color_hex;
} comp_bp_metric_summary_card_data_t;

lv_obj_t *comp_bp_metric_summary_card_create(
    lv_obj_t *parent, const comp_bp_metric_summary_card_data_t *data);

#endif
