#ifndef COMP_USER_CARD_H
#define COMP_USER_CARD_H

#include <stdint.h>

#include "lvgl.h"
#include "health_ui_display_policy.h"
#include "../../layout/layout_fonts.h"

#ifndef COMP_USER_CARD_WIDTH_PCT
#if (MY_DISP_HOR_RES >= 1024)
#define COMP_USER_CARD_WIDTH_PCT (24)
#else
#define COMP_USER_CARD_WIDTH_PCT (31)
#endif
#endif

#ifndef COMP_USER_CARD_RADIUS_PX
#define COMP_USER_CARD_RADIUS_PX (20)
#endif

#ifndef COMP_USER_CARD_AVATAR_SIZE_PX
#define COMP_USER_CARD_AVATAR_SIZE_PX HL_SCALE_V(96)
#endif

#ifndef COMP_USER_CARD_AVATAR_TOP_OFFSET_PX
#define COMP_USER_CARD_AVATAR_TOP_OFFSET_PX (0)
#endif

#ifndef COMP_USER_CARD_PAD_HOR_PX
#define COMP_USER_CARD_PAD_HOR_PX (8)
#endif

#ifndef COMP_USER_CARD_PAD_TOP_PX
#define COMP_USER_CARD_PAD_TOP_PX HL_SCALE_V(8)
#endif

#ifndef COMP_USER_CARD_PAD_BOTTOM_PX
#define COMP_USER_CARD_PAD_BOTTOM_PX HL_SCALE_V(8)
#endif

#ifndef COMP_USER_CARD_ROW_GAP_PX
#define COMP_USER_CARD_ROW_GAP_PX HL_SCALE_V(6)
#endif

#ifndef COMP_USER_CARD_BG_COLOR_HEX
#define COMP_USER_CARD_BG_COLOR_HEX (0xF2F3F5)
#endif

#ifndef COMP_USER_CARD_AVATAR_BG_COLOR_HEX
#define COMP_USER_CARD_AVATAR_BG_COLOR_HEX (0xD6DCE4)
#endif

#ifndef COMP_USER_CARD_NAME_COLOR_HEX
#define COMP_USER_CARD_NAME_COLOR_HEX (0x101828)
#endif

/* Primary user name typography knob. */
#ifndef COMP_USER_CARD_NAME_FONT
#define COMP_USER_CARD_NAME_FONT HL_FONT_TITLE
#endif

#ifndef COMP_USER_CARD_MAX_VISIBLE_CHIPS
#define COMP_USER_CARD_MAX_VISIBLE_CHIPS (2U)
#endif

#ifndef COMP_USER_CARD_ENABLE_MORE_CHIP
#define COMP_USER_CARD_ENABLE_MORE_CHIP (1U)
#endif

#ifndef COMP_USER_CARD_CHIP_HEIGHT_PX
#define COMP_USER_CARD_CHIP_HEIGHT_PX HL_SCALE_V(26)
#endif

#ifndef COMP_USER_CARD_CHIP_RADIUS_PX
#define COMP_USER_CARD_CHIP_RADIUS_PX (13)
#endif

#ifndef COMP_USER_CARD_CHIP_TEXT_COLOR_NORMAL_HEX
#define COMP_USER_CARD_CHIP_TEXT_COLOR_NORMAL_HEX (0x98A2B3)
#endif

#ifndef COMP_USER_CARD_CHIP_BG_COLOR_NORMAL_HEX
#define COMP_USER_CARD_CHIP_BG_COLOR_NORMAL_HEX (0xFFFFFF)
#endif

#ifndef COMP_USER_CARD_CHIP_TEXT_COLOR_WARNING_HEX
#define COMP_USER_CARD_CHIP_TEXT_COLOR_WARNING_HEX (0x8A5A00)
#endif

#ifndef COMP_USER_CARD_CHIP_BG_COLOR_WARNING_HEX
#define COMP_USER_CARD_CHIP_BG_COLOR_WARNING_HEX (0xFDEFCF)
#endif

#ifndef COMP_USER_CARD_CHIP_BORDER_COLOR_WARNING_HEX
#define COMP_USER_CARD_CHIP_BORDER_COLOR_WARNING_HEX (0xF2CF66)
#endif

#ifndef COMP_USER_CARD_CHIP_TEXT_COLOR_CRITICAL_HEX
#define COMP_USER_CARD_CHIP_TEXT_COLOR_CRITICAL_HEX (0xB42318)
#endif

#ifndef COMP_USER_CARD_CHIP_BG_COLOR_CRITICAL_HEX
#define COMP_USER_CARD_CHIP_BG_COLOR_CRITICAL_HEX (0xFDE1E1)
#endif

#ifndef COMP_USER_CARD_CHIP_BORDER_COLOR_CRITICAL_HEX
#define COMP_USER_CARD_CHIP_BORDER_COLOR_CRITICAL_HEX (0xF59AA0)
#endif

#ifndef COMP_USER_CARD_CHIP_TEXT_COLOR_MORE_HEX
#define COMP_USER_CARD_CHIP_TEXT_COLOR_MORE_HEX (0x475467)
#endif

#ifndef COMP_USER_CARD_CHIP_BG_COLOR_MORE_HEX
#define COMP_USER_CARD_CHIP_BG_COLOR_MORE_HEX (0xEAECF0)
#endif

#ifndef COMP_USER_CARD_CHIP_ROW_GAP_PX
#define COMP_USER_CARD_CHIP_ROW_GAP_PX (8)
#endif

#ifndef COMP_USER_CARD_CHIP_PAD_HOR_PX
#define COMP_USER_CARD_CHIP_PAD_HOR_PX (10)
#endif

#ifndef COMP_USER_CARD_CHIP_PAD_VER_PX
#define COMP_USER_CARD_CHIP_PAD_VER_PX HL_SCALE_V(1)
#endif

#ifndef COMP_USER_CARD_CHIP_FONT
#define COMP_USER_CARD_CHIP_FONT HL_FONT_CAPTION
#endif

#ifndef COMP_USER_CARD_MORE_CHIP_USES_VISIBLE_SLOT
#define COMP_USER_CARD_MORE_CHIP_USES_VISIBLE_SLOT (1U)
#endif

#ifndef COMP_USER_CARD_METRIC_PANEL_HEIGHT_PX
#define COMP_USER_CARD_METRIC_PANEL_HEIGHT_PX HL_SCALE_V(88)
#endif

#ifndef COMP_USER_CARD_METRIC_PANEL_RADIUS_PX
#define COMP_USER_CARD_METRIC_PANEL_RADIUS_PX (14)
#endif

#ifndef COMP_USER_CARD_METRIC_PANEL_BG_COLOR_HEX
#define COMP_USER_CARD_METRIC_PANEL_BG_COLOR_HEX (0xF7F8FA)
#endif

#ifndef COMP_USER_CARD_METRIC_TITLE_COLOR_HEX
#define COMP_USER_CARD_METRIC_TITLE_COLOR_HEX (0x101828)
#endif

#ifndef COMP_USER_CARD_METRIC_VALUE_COLOR_HEX
#define COMP_USER_CARD_METRIC_VALUE_COLOR_HEX (0x101828)
#endif

#ifndef COMP_USER_CARD_METRIC_MUTED_COLOR_HEX
#define COMP_USER_CARD_METRIC_MUTED_COLOR_HEX (0x8A94A2)
#endif

#ifndef COMP_USER_CARD_METRIC_STATUS_NORMAL_COLOR_HEX
#define COMP_USER_CARD_METRIC_STATUS_NORMAL_COLOR_HEX (0x8A94A2)
#endif

#ifndef COMP_USER_CARD_METRIC_STATUS_WARNING_COLOR_HEX
#define COMP_USER_CARD_METRIC_STATUS_WARNING_COLOR_HEX (0xF5A524)
#endif

#ifndef COMP_USER_CARD_METRIC_STATUS_CRITICAL_COLOR_HEX
#define COMP_USER_CARD_METRIC_STATUS_CRITICAL_COLOR_HEX (0xEF4F4F)
#endif

#ifndef COMP_USER_CARD_METRIC_ICON_BG_COLOR_HEX
#define COMP_USER_CARD_METRIC_ICON_BG_COLOR_HEX (0xE5E7EB)
#endif

#ifndef COMP_USER_CARD_METRIC_ICON_TEXT_COLOR_HEX
#define COMP_USER_CARD_METRIC_ICON_TEXT_COLOR_HEX (0x667085)
#endif

#ifndef COMP_USER_CARD_METRIC_PANEL_PAD_HOR_PX
#define COMP_USER_CARD_METRIC_PANEL_PAD_HOR_PX (10)
#endif

#ifndef COMP_USER_CARD_METRIC_PANEL_PAD_TOP_PX
#define COMP_USER_CARD_METRIC_PANEL_PAD_TOP_PX HL_SCALE_V(8)
#endif

#ifndef COMP_USER_CARD_METRIC_PANEL_PAD_BOTTOM_PX
#define COMP_USER_CARD_METRIC_PANEL_PAD_BOTTOM_PX HL_SCALE_V(8)
#endif

#ifndef COMP_USER_CARD_METRIC_PANEL_ROW_GAP_PX
#define COMP_USER_CARD_METRIC_PANEL_ROW_GAP_PX HL_SCALE_V(6)
#endif

#ifndef COMP_USER_CARD_METRIC_TOP_ROW_GAP_PX
#define COMP_USER_CARD_METRIC_TOP_ROW_GAP_PX (8)
#endif

#ifndef COMP_USER_CARD_METRIC_LEFT_GROUP_GAP_PX
#define COMP_USER_CARD_METRIC_LEFT_GROUP_GAP_PX (8)
#endif

#ifndef COMP_USER_CARD_METRIC_VALUE_GROUP_GAP_PX
#define COMP_USER_CARD_METRIC_VALUE_GROUP_GAP_PX (8)
#endif

#ifndef COMP_USER_CARD_METRIC_STATUS_GROUP_GAP_PX
/* Gap between bullet and status text in bottom-right metric row. */
#define COMP_USER_CARD_METRIC_STATUS_GROUP_GAP_PX (2)
#endif

#ifndef COMP_USER_CARD_METRIC_STATUS_GROUP_LEFT_PAD_PX
#define COMP_USER_CARD_METRIC_STATUS_GROUP_LEFT_PAD_PX (0)
#endif

#ifndef COMP_USER_CARD_METRIC_STATUS_GROUP_WIDTH_PX
/* Fixed right slot keeps status aligned with top-right time text lane. */
#define COMP_USER_CARD_METRIC_STATUS_GROUP_WIDTH_PX (118)
#endif

#ifndef COMP_USER_CARD_METRIC_ICON_SIZE_PX
#define COMP_USER_CARD_METRIC_ICON_SIZE_PX (24)
#endif

#ifndef COMP_USER_CARD_METRIC_ICON_FONT
#define COMP_USER_CARD_METRIC_ICON_FONT HL_FONT_CAPTION
#endif

#ifndef COMP_USER_CARD_METRIC_TITLE_FONT
#define COMP_USER_CARD_METRIC_TITLE_FONT HL_FONT_BODY
#endif

#ifndef COMP_USER_CARD_METRIC_TIME_FONT
#define COMP_USER_CARD_METRIC_TIME_FONT HL_FONT_SMALL
#endif

#ifndef COMP_USER_CARD_METRIC_TIME_MIN_WIDTH_PX
#define COMP_USER_CARD_METRIC_TIME_MIN_WIDTH_PX (38)
#endif

/* Primary latest-value typography knob (value_text). */
#ifndef COMP_USER_CARD_METRIC_VALUE_FONT
#define COMP_USER_CARD_METRIC_VALUE_FONT HL_FONT_HEADING
#endif

#ifndef COMP_USER_CARD_METRIC_UNIT_FONT
#define COMP_USER_CARD_METRIC_UNIT_FONT HL_FONT_CAPTION
#endif

#ifndef COMP_USER_CARD_METRIC_STATUS_FONT
#define COMP_USER_CARD_METRIC_STATUS_FONT HL_FONT_CAPTION
#endif

#ifndef COMP_USER_CARD_METRIC_TITLE_MAX_WIDTH_PX
#define COMP_USER_CARD_METRIC_TITLE_MAX_WIDTH_PX (152)
#endif

#ifndef COMP_USER_CARD_METRIC_STATUS_MAX_WIDTH_PX
#define COMP_USER_CARD_METRIC_STATUS_MAX_WIDTH_PX (96)
#endif

typedef enum {
  COMP_USER_CONDITION_NORMAL = 0,
  COMP_USER_CONDITION_LOW_FEVER = 1,
  COMP_USER_CONDITION_HIGH_FEVER = 2,
  COMP_USER_CONDITION_PREDIABETES = 3
} comp_user_condition_t;

typedef enum {
  COMP_USER_METRIC_BLOOD_PRESSURE = 0,
  COMP_USER_METRIC_BODY_TEMP = 1,
  COMP_USER_METRIC_BLOOD_GLUCOSE = 2
} comp_user_metric_type_t;

typedef enum {
  COMP_USER_STATUS_NORMAL = 0,
  COMP_USER_STATUS_WARNING = 1,
  COMP_USER_STATUS_CRITICAL = 2
} comp_user_status_level_t;

typedef struct {
  comp_user_metric_type_t type;
  const char *value_text;
  const char *unit_text;
  const char *status_text;
  const char *time_text;
  comp_user_status_level_t status_level;
} comp_user_metric_preview_t;

typedef struct {
  const char *name;
  /* Reserved for future variant themes. Current design keeps card background fixed. */
  uint32_t card_bg_color_hex;
  uint32_t avatar_bg_color_hex;
  /* Sim/runtime metadata used by detail page/header binding. */
  uint32_t age_years;
  const comp_user_condition_t *conditions;
  uint32_t condition_count;
  comp_user_metric_preview_t metric;
} comp_user_card_data_t;

lv_obj_t *comp_user_card_create(lv_obj_t *parent,
                                const comp_user_card_data_t *data);

#endif
