#ifndef XENSIV_DPS3XX_H
#define XENSIV_DPS3XX_H
#define XENSIV_DPS3XX_RATE_1           1
#define XENSIV_DPS3XX_OVERSAMPLE_8     8
#define XENSIV_DPS3XX_I2C_ADDR_DEFAULT 0x77
#define XENSIV_DPS3XX_I2C_ADDR_ALT     0x76
#endif
