#ifndef COMP_ADD_DEVICE_LIST_ITEM_H
#define COMP_ADD_DEVICE_LIST_ITEM_H

#include <stdbool.h>
#include <stdint.h>

#include "lvgl.h"
#include "../../layout/layout_fonts.h"

#ifndef COMP_ADD_DEVICE_LIST_ITEM_HEIGHT_PX
#define COMP_ADD_DEVICE_LIST_ITEM_HEIGHT_PX (74)
#endif

#ifndef COMP_ADD_DEVICE_LIST_ITEM_SIDE_PAD_PX
#define COMP_ADD_DEVICE_LIST_ITEM_SIDE_PAD_PX (10)
#endif

#ifndef COMP_ADD_DEVICE_LIST_ITEM_COL_GAP_PX
#define COMP_ADD_DEVICE_LIST_ITEM_COL_GAP_PX (10)
#endif

#ifndef COMP_ADD_DEVICE_LIST_ITEM_BG_COLOR_HEX
#define COMP_ADD_DEVICE_LIST_ITEM_BG_COLOR_HEX (0xFFFFFF)
#endif

#ifndef COMP_ADD_DEVICE_LIST_ITEM_AVATAR_SIZE_PX
#define COMP_ADD_DEVICE_LIST_ITEM_AVATAR_SIZE_PX (50)
#endif

#ifndef COMP_ADD_DEVICE_LIST_ITEM_AVATAR_RADIUS_PX
#define COMP_ADD_DEVICE_LIST_ITEM_AVATAR_RADIUS_PX (25)
#endif

#ifndef COMP_ADD_DEVICE_LIST_ITEM_AVATAR_BG_COLOR_HEX
#define COMP_ADD_DEVICE_LIST_ITEM_AVATAR_BG_COLOR_HEX (0xE7EAF0)
#endif

#ifndef COMP_ADD_DEVICE_LIST_ITEM_AVATAR_TEXT_COLOR_HEX
#define COMP_ADD_DEVICE_LIST_ITEM_AVATAR_TEXT_COLOR_HEX (0x667085)
#endif

#ifndef COMP_ADD_DEVICE_LIST_ITEM_AVATAR_FONT
#define COMP_ADD_DEVICE_LIST_ITEM_AVATAR_FONT HL_FONT_BODY
#endif

#ifndef COMP_ADD_DEVICE_LIST_ITEM_TEXT_ROW_GAP_PX
#define COMP_ADD_DEVICE_LIST_ITEM_TEXT_ROW_GAP_PX (2)
#endif

#ifndef COMP_ADD_DEVICE_LIST_ITEM_NAME_COLOR_HEX
#define COMP_ADD_DEVICE_LIST_ITEM_NAME_COLOR_HEX (0x1D2939)
#endif

#ifndef COMP_ADD_DEVICE_LIST_ITEM_NAME_FONT
#define COMP_ADD_DEVICE_LIST_ITEM_NAME_FONT HL_FONT_BODY
#endif

#ifndef COMP_ADD_DEVICE_LIST_ITEM_TYPE_COLOR_HEX
#define COMP_ADD_DEVICE_LIST_ITEM_TYPE_COLOR_HEX (0x8A94A2)
#endif

#ifndef COMP_ADD_DEVICE_LIST_ITEM_TYPE_FONT
#define COMP_ADD_DEVICE_LIST_ITEM_TYPE_FONT HL_FONT_CAPTION
#endif

#ifndef COMP_ADD_DEVICE_LIST_ITEM_CHEVRON_TEXT
#define COMP_ADD_DEVICE_LIST_ITEM_CHEVRON_TEXT ">"
#endif

#ifndef COMP_ADD_DEVICE_LIST_ITEM_CHEVRON_COLOR_HEX
#define COMP_ADD_DEVICE_LIST_ITEM_CHEVRON_COLOR_HEX (0x667085)
#endif

#ifndef COMP_ADD_DEVICE_LIST_ITEM_CHEVRON_FONT
#define COMP_ADD_DEVICE_LIST_ITEM_CHEVRON_FONT HL_FONT_TITLE
#endif

#ifndef COMP_ADD_DEVICE_LIST_ITEM_DIVIDER_COLOR_HEX
#define COMP_ADD_DEVICE_LIST_ITEM_DIVIDER_COLOR_HEX (0xDDE1E6)
#endif

#ifndef COMP_ADD_DEVICE_LIST_ITEM_DIVIDER_WIDTH_PX
#define COMP_ADD_DEVICE_LIST_ITEM_DIVIDER_WIDTH_PX (1)
#endif

typedef struct {
  const char *name;
  const char *type_text;
  const char *avatar_text;
  uint32_t avatar_bg_color_hex;
  bool show_divider;
} comp_add_device_list_item_data_t;

lv_obj_t *comp_add_device_list_item_create(
    lv_obj_t *parent, const comp_add_device_list_item_data_t *data);

#endif
