#ifndef COMP_ADD_DEVICE_FLOW_MODAL_H
#define COMP_ADD_DEVICE_FLOW_MODAL_H

#include <stdbool.h>

#include "lvgl.h"
#include "health_ui_display_policy.h"
#include "../../layout/layout_fonts.h"

/* Local style knobs for Add Device modal only. */
#ifndef ADD_DEVICE_MODAL_SURFACE_COLOR_HEX
#define ADD_DEVICE_MODAL_SURFACE_COLOR_HEX (0xF2F3F5)
#endif

#ifndef ADD_DEVICE_MODAL_HEADER_BG_COLOR_HEX
#define ADD_DEVICE_MODAL_HEADER_BG_COLOR_HEX (0xF2F3F5)
#endif

#ifndef ADD_DEVICE_MODAL_TEXT_COLOR_HEX
#define ADD_DEVICE_MODAL_TEXT_COLOR_HEX (0x002329)
#endif

#ifndef ADD_DEVICE_MODAL_BACKDROP_COLOR_HEX
#define ADD_DEVICE_MODAL_BACKDROP_COLOR_HEX (0x000000)
#endif

#ifndef ADD_DEVICE_MODAL_BACKDROP_OPA
#define ADD_DEVICE_MODAL_BACKDROP_OPA (LV_OPA_40)
#endif

#ifndef ADD_DEVICE_MODAL_WIDTH_PERCENT
#define ADD_DEVICE_MODAL_WIDTH_PERCENT (60)
#endif

#ifndef ADD_DEVICE_MODAL_HEIGHT_PERCENT
#define ADD_DEVICE_MODAL_HEIGHT_PERCENT (80)
#endif

#ifndef ADD_DEVICE_MODAL_RADIUS_PX
#define ADD_DEVICE_MODAL_RADIUS_PX (20)
#endif

#ifndef ADD_DEVICE_MODAL_PAD_H_PX
#define ADD_DEVICE_MODAL_PAD_H_PX (16)
#endif

#ifndef ADD_DEVICE_MODAL_PAD_V_PX
#define ADD_DEVICE_MODAL_PAD_V_PX HL_SCALE_V(12)
#endif

#ifndef ADD_DEVICE_MODAL_CONTENT_TOP_PAD_PX
#define ADD_DEVICE_MODAL_CONTENT_TOP_PAD_PX HL_SCALE_V(8)
#endif

#ifndef ADD_DEVICE_MODAL_CONTENT_BOTTOM_PAD_PX
#define ADD_DEVICE_MODAL_CONTENT_BOTTOM_PAD_PX HL_SCALE_V(12)
#endif

#ifndef ADD_DEVICE_MODAL_CONTENT_SCROLLABLE
#define ADD_DEVICE_MODAL_CONTENT_SCROLLABLE (0)
#endif

#ifndef ADD_DEVICE_MODAL_LIST_PANEL_BG_COLOR_HEX
#define ADD_DEVICE_MODAL_LIST_PANEL_BG_COLOR_HEX (0xF7F8FA)
#endif

#ifndef ADD_DEVICE_MODAL_LIST_PANEL_RADIUS_PX
#define ADD_DEVICE_MODAL_LIST_PANEL_RADIUS_PX (14)
#endif

#ifndef ADD_DEVICE_MODAL_LIST_PANEL_PAD_H_PX
#define ADD_DEVICE_MODAL_LIST_PANEL_PAD_H_PX (8)
#endif

#ifndef ADD_DEVICE_MODAL_LIST_PANEL_PAD_V_PX
#define ADD_DEVICE_MODAL_LIST_PANEL_PAD_V_PX HL_SCALE_V(4)
#endif

#ifndef ADD_DEVICE_MODAL_TITLE_TEXT
#define ADD_DEVICE_MODAL_TITLE_TEXT "Add Device"
#endif

#ifndef ADD_DEVICE_MODAL_TITLE_FONT
#define ADD_DEVICE_MODAL_TITLE_FONT HL_FONT_HEADING
#endif

#ifndef ADD_DEVICE_MODAL_CLOSE_FONT
#define ADD_DEVICE_MODAL_CLOSE_FONT HL_FONT_HEADING
#endif

#ifndef ADD_DEVICE_MODAL_CLOSE_LABEL_TEXT
#define ADD_DEVICE_MODAL_CLOSE_LABEL_TEXT "X"
#endif

#ifndef ADD_DEVICE_MODAL_BACK_LABEL_TEXT
#define ADD_DEVICE_MODAL_BACK_LABEL_TEXT "<"
#endif

#ifndef ADD_DEVICE_MODAL_SHOW_BACK_ICON
#define ADD_DEVICE_MODAL_SHOW_BACK_ICON (0)
#endif

#ifndef ADD_DEVICE_MODAL_HEADER_SIDE_SLOT_W_PX
#define ADD_DEVICE_MODAL_HEADER_SIDE_SLOT_W_PX (44)
#endif

#ifndef ADD_DEVICE_MODAL_HEADER_SIDE_SLOT_H_PX
#define ADD_DEVICE_MODAL_HEADER_SIDE_SLOT_H_PX HL_SCALE_V(36)
#endif

#ifndef ADD_DEVICE_MODAL_HEADER_BACK_PAD_LEFT_PX
#define ADD_DEVICE_MODAL_HEADER_BACK_PAD_LEFT_PX (4)
#endif

#ifndef ADD_DEVICE_MODAL_HEADER_BACK_FONT
#define ADD_DEVICE_MODAL_HEADER_BACK_FONT HL_FONT_HEADING
#endif

#ifndef ADD_DEVICE_MODAL_MAX_LIST_ITEMS
#define ADD_DEVICE_MODAL_MAX_LIST_ITEMS (16U)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_TOP_PAD_PX
#define ADD_DEVICE_MODAL_STEP_TOP_PAD_PX HL_SCALE_V(4)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_ROW_GAP_PX
#define ADD_DEVICE_MODAL_STEP_ROW_GAP_PX HL_SCALE_V(12)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_BOTTOM_PAD_PX
#define ADD_DEVICE_MODAL_STEP_BOTTOM_PAD_PX HL_SCALE_V(2)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_MAIN_ALIGN
#define ADD_DEVICE_MODAL_STEP_MAIN_ALIGN (LV_FLEX_ALIGN_START)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_IMAGE_BOX_SIZE_PX
#define ADD_DEVICE_MODAL_STEP_IMAGE_BOX_SIZE_PX HL_SCALE_V(148)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_IMAGE_BOX_RADIUS_PX
#define ADD_DEVICE_MODAL_STEP_IMAGE_BOX_RADIUS_PX (28)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_IMAGE_BOX_BG_COLOR_HEX
#define ADD_DEVICE_MODAL_STEP_IMAGE_BOX_BG_COLOR_HEX (0xECEEF2)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_IMAGE_BOX_BORDER_COLOR_HEX
#define ADD_DEVICE_MODAL_STEP_IMAGE_BOX_BORDER_COLOR_HEX (0xD8DDE5)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_IMAGE_TEXT_COLOR_HEX
#define ADD_DEVICE_MODAL_STEP_IMAGE_TEXT_COLOR_HEX (0x8A94A2)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_IMAGE_FONT
#define ADD_DEVICE_MODAL_STEP_IMAGE_FONT HL_FONT_BODY
#endif

#ifndef ADD_DEVICE_MODAL_STEP_GUIDE_COLOR_HEX
#define ADD_DEVICE_MODAL_STEP_GUIDE_COLOR_HEX (0x475467)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_GUIDE_FONT
#define ADD_DEVICE_MODAL_STEP_GUIDE_FONT HL_FONT_BODY
#endif

#ifndef ADD_DEVICE_MODAL_STEP_GUIDE_WIDTH_PCT
#define ADD_DEVICE_MODAL_STEP_GUIDE_WIDTH_PCT (76)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_GUIDE_HEIGHT_PX
#define ADD_DEVICE_MODAL_STEP_GUIDE_HEIGHT_PX HL_SCALE_V(56)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_GUIDE_SIDE_PAD_PX
#define ADD_DEVICE_MODAL_STEP_GUIDE_SIDE_PAD_PX (6)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_FORCE_STATIC_GUIDE_TEXT
#define ADD_DEVICE_MODAL_STEP_FORCE_STATIC_GUIDE_TEXT (0)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_STATIC_GUIDE_TEXT
#define ADD_DEVICE_MODAL_STEP_STATIC_GUIDE_TEXT \
  "Static guide text test: keep device near gateway."
#endif

#ifndef ADD_DEVICE_MODAL_STEP_CTA_WIDTH_PX
#define ADD_DEVICE_MODAL_STEP_CTA_WIDTH_PX (176)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_CTA_HEIGHT_PX
#define ADD_DEVICE_MODAL_STEP_CTA_HEIGHT_PX HL_SCALE_V(44)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_CTA_RADIUS_PX
#define ADD_DEVICE_MODAL_STEP_CTA_RADIUS_PX (26)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_CTA_BG_COLOR_HEX
#define ADD_DEVICE_MODAL_STEP_CTA_BG_COLOR_HEX (0x4A89E8)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_CTA_TEXT_COLOR_HEX
#define ADD_DEVICE_MODAL_STEP_CTA_TEXT_COLOR_HEX (0xFFFFFF)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_CTA_FONT
#define ADD_DEVICE_MODAL_STEP_CTA_FONT HL_FONT_BODY
#endif

/* Debug colors for Step modal layout zoning. Keep disabled in production. */
#ifndef ADD_DEVICE_MODAL_STEP_DEBUG_LAYOUT
#define ADD_DEVICE_MODAL_STEP_DEBUG_LAYOUT (0)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_DEBUG_OPA
#define ADD_DEVICE_MODAL_STEP_DEBUG_OPA (LV_OPA_30)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_DEBUG_HEADER_COLOR_HEX
#define ADD_DEVICE_MODAL_STEP_DEBUG_HEADER_COLOR_HEX (0xFFD6D6)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_DEBUG_CONTENT_COLOR_HEX
#define ADD_DEVICE_MODAL_STEP_DEBUG_CONTENT_COLOR_HEX (0xD6E9FF)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_DEBUG_ROOT_COLOR_HEX
#define ADD_DEVICE_MODAL_STEP_DEBUG_ROOT_COLOR_HEX (0xD9F8D9)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_DEBUG_INDICATOR_COLOR_HEX
#define ADD_DEVICE_MODAL_STEP_DEBUG_INDICATOR_COLOR_HEX (0xFFF0C2)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_DEBUG_IMAGE_COLOR_HEX
#define ADD_DEVICE_MODAL_STEP_DEBUG_IMAGE_COLOR_HEX (0xE7DBFF)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_DEBUG_GUIDE_COLOR_HEX
#define ADD_DEVICE_MODAL_STEP_DEBUG_GUIDE_COLOR_HEX (0xFFE2BF)
#endif

#ifndef ADD_DEVICE_MODAL_STEP_DEBUG_CTA_COLOR_HEX
#define ADD_DEVICE_MODAL_STEP_DEBUG_CTA_COLOR_HEX (0xCFF2FF)
#endif

void comp_add_device_flow_modal_open(void);
void comp_add_device_flow_modal_close(void);
bool comp_add_device_flow_modal_is_open(void);

#endif
