#ifndef COMP_ADD_DEVICE_STEP_INDICATOR_H
#define COMP_ADD_DEVICE_STEP_INDICATOR_H

#include <stdint.h>

#include "lvgl.h"
#include "../../layout/layout_fonts.h"

#ifndef COMP_ADD_DEVICE_STEP_INDICATOR_HEIGHT_PX
#define COMP_ADD_DEVICE_STEP_INDICATOR_HEIGHT_PX (56)
#endif

#ifndef COMP_ADD_DEVICE_STEP_INDICATOR_CIRCLE_SIZE_PX
#define COMP_ADD_DEVICE_STEP_INDICATOR_CIRCLE_SIZE_PX (42)
#endif

#ifndef COMP_ADD_DEVICE_STEP_INDICATOR_CIRCLE_RADIUS_PX
#define COMP_ADD_DEVICE_STEP_INDICATOR_CIRCLE_RADIUS_PX (21)
#endif

#ifndef COMP_ADD_DEVICE_STEP_INDICATOR_LINE_HEIGHT_PX
#define COMP_ADD_DEVICE_STEP_INDICATOR_LINE_HEIGHT_PX (2)
#endif

#ifndef COMP_ADD_DEVICE_STEP_INDICATOR_ACTIVE_BG_COLOR_HEX
#define COMP_ADD_DEVICE_STEP_INDICATOR_ACTIVE_BG_COLOR_HEX (0x4A89E8)
#endif

#ifndef COMP_ADD_DEVICE_STEP_INDICATOR_ACTIVE_TEXT_COLOR_HEX
#define COMP_ADD_DEVICE_STEP_INDICATOR_ACTIVE_TEXT_COLOR_HEX (0xFFFFFF)
#endif

#ifndef COMP_ADD_DEVICE_STEP_INDICATOR_INACTIVE_BG_COLOR_HEX
#define COMP_ADD_DEVICE_STEP_INDICATOR_INACTIVE_BG_COLOR_HEX (0xE9ECF1)
#endif

#ifndef COMP_ADD_DEVICE_STEP_INDICATOR_INACTIVE_TEXT_COLOR_HEX
#define COMP_ADD_DEVICE_STEP_INDICATOR_INACTIVE_TEXT_COLOR_HEX (0x8A94A2)
#endif

#ifndef COMP_ADD_DEVICE_STEP_INDICATOR_LINE_ACTIVE_COLOR_HEX
#define COMP_ADD_DEVICE_STEP_INDICATOR_LINE_ACTIVE_COLOR_HEX (0x4A89E8)
#endif

#ifndef COMP_ADD_DEVICE_STEP_INDICATOR_LINE_INACTIVE_COLOR_HEX
#define COMP_ADD_DEVICE_STEP_INDICATOR_LINE_INACTIVE_COLOR_HEX (0xDDE3EB)
#endif

#ifndef COMP_ADD_DEVICE_STEP_INDICATOR_FONT
#define COMP_ADD_DEVICE_STEP_INDICATOR_FONT HL_FONT_BODY
#endif

/* active_step is 1..total_steps (clamped). */
lv_obj_t *comp_add_device_step_indicator_create(lv_obj_t *parent, uint32_t active_step,
                                                uint32_t total_steps);

#endif
