#ifndef PAGE_METRIC_BP_DETAIL_LAYOUT_H
#define PAGE_METRIC_BP_DETAIL_LAYOUT_H

#include "../../sim/health_ui_sim_data.h"

#include "lvgl.h"
#include "../../health_ui_display_policy.h"
#include "../../layout/layout_fonts.h"

/* Main surface */
#ifndef METRIC_BP_DETAIL_PANEL_BG_COLOR_HEX
#define METRIC_BP_DETAIL_PANEL_BG_COLOR_HEX (0xF2F3F5)
#endif

#ifndef METRIC_BP_DETAIL_PANEL_RADIUS_PX
#define METRIC_BP_DETAIL_PANEL_RADIUS_PX (20)
#endif

#ifndef METRIC_BP_DETAIL_PANEL_PAD_PX
#define METRIC_BP_DETAIL_PANEL_PAD_PX (16)
#endif

#ifndef METRIC_BP_DETAIL_PANEL_ROW_GAP_PX
#define METRIC_BP_DETAIL_PANEL_ROW_GAP_PX (10)
#endif

/* Typography */
#ifndef METRIC_BP_DETAIL_TITLE_FONT
#define METRIC_BP_DETAIL_TITLE_FONT HL_FONT_HERO
#endif

#ifndef METRIC_BP_DETAIL_TITLE_COLOR_HEX
#define METRIC_BP_DETAIL_TITLE_COLOR_HEX (0x002329)
#endif

#ifndef METRIC_BP_DETAIL_PERIOD_FONT
#define METRIC_BP_DETAIL_PERIOD_FONT HL_FONT_HEADING
#endif

#ifndef METRIC_BP_DETAIL_PERIOD_TEXT_COLOR_HEX
#define METRIC_BP_DETAIL_PERIOD_TEXT_COLOR_HEX (0x1D2939)
#endif

/* Period controls */
#ifndef METRIC_BP_DETAIL_PERIOD_BTN_SIZE_PX
#define METRIC_BP_DETAIL_PERIOD_BTN_SIZE_PX HL_SCALE_V(38)
#endif

#ifndef METRIC_BP_DETAIL_PERIOD_BTN_BG_COLOR_HEX
#define METRIC_BP_DETAIL_PERIOD_BTN_BG_COLOR_HEX (0xE7E8EB)
#endif

#ifndef METRIC_BP_DETAIL_PERIOD_BTN_TEXT_FONT
#define METRIC_BP_DETAIL_PERIOD_BTN_TEXT_FONT HL_FONT_BODY
#endif

#ifndef METRIC_BP_DETAIL_PERIOD_BTN_TEXT_COLOR_HEX
#define METRIC_BP_DETAIL_PERIOD_BTN_TEXT_COLOR_HEX (0x101828)
#endif

#ifndef METRIC_BP_DETAIL_PERIOD_CHIP_MIN_W_PX
#define METRIC_BP_DETAIL_PERIOD_CHIP_MIN_W_PX (232)
#endif

#ifndef METRIC_BP_DETAIL_PERIOD_CHIP_HEIGHT_PX
#define METRIC_BP_DETAIL_PERIOD_CHIP_HEIGHT_PX HL_SCALE_V(38)
#endif

#ifndef METRIC_BP_DETAIL_PERIOD_CHIP_RADIUS_PX
#define METRIC_BP_DETAIL_PERIOD_CHIP_RADIUS_PX (22)
#endif

#ifndef METRIC_BP_DETAIL_PERIOD_CHIP_BG_COLOR_HEX
#define METRIC_BP_DETAIL_PERIOD_CHIP_BG_COLOR_HEX (0xE7E8EB)
#endif

/* Summary cards row */
#ifndef METRIC_BP_DETAIL_SUMMARY_ROW_H_PX
#define METRIC_BP_DETAIL_SUMMARY_ROW_H_PX HL_SCALE_V(114)
#endif

#ifndef METRIC_BP_DETAIL_SUMMARY_COL_GAP_PX
#define METRIC_BP_DETAIL_SUMMARY_COL_GAP_PX (12)
#endif

/* Chart card */
#ifndef METRIC_BP_DETAIL_CHART_PANEL_H_PX
#define METRIC_BP_DETAIL_CHART_PANEL_H_PX HL_SCALE_V(236)
#endif

#ifndef METRIC_BP_DETAIL_CHART_PANEL_BG_COLOR_HEX
#define METRIC_BP_DETAIL_CHART_PANEL_BG_COLOR_HEX (0xF7F8FA)
#endif

#ifndef METRIC_BP_DETAIL_CHART_PANEL_RADIUS_PX
#define METRIC_BP_DETAIL_CHART_PANEL_RADIUS_PX (14)
#endif

#ifndef METRIC_BP_DETAIL_CHART_PANEL_PAD_PX
#define METRIC_BP_DETAIL_CHART_PANEL_PAD_PX (12)
#endif

#ifndef METRIC_BP_DETAIL_CHART_LEFT_AXIS_W_PX
#define METRIC_BP_DETAIL_CHART_LEFT_AXIS_W_PX (68)
#endif

#ifndef METRIC_BP_DETAIL_CHART_RIGHT_AXIS_W_PX
#define METRIC_BP_DETAIL_CHART_RIGHT_AXIS_W_PX (58)
#endif

#ifndef METRIC_BP_DETAIL_AXIS_LABEL_FONT
#define METRIC_BP_DETAIL_AXIS_LABEL_FONT HL_FONT_BODY
#endif

#ifndef METRIC_BP_DETAIL_AXIS_TEXT_COLOR_HEX
#define METRIC_BP_DETAIL_AXIS_TEXT_COLOR_HEX (0x667085)
#endif

#ifndef METRIC_BP_DETAIL_CHART_LINE_WIDTH_PX
#define METRIC_BP_DETAIL_CHART_LINE_WIDTH_PX (2)
#endif

#ifndef METRIC_BP_DETAIL_CHART_POINT_SIZE_PX
#define METRIC_BP_DETAIL_CHART_POINT_SIZE_PX (8)
#endif

#ifndef METRIC_BP_DETAIL_CHART_DIV_LINE_COLOR_HEX
#define METRIC_BP_DETAIL_CHART_DIV_LINE_COLOR_HEX (0xD9DEE5)
#endif

#ifndef METRIC_BP_DETAIL_X_LABEL_FONT
#define METRIC_BP_DETAIL_X_LABEL_FONT HL_FONT_BODY
#endif

#ifndef METRIC_BP_DETAIL_X_LABEL_COLOR_HEX
#define METRIC_BP_DETAIL_X_LABEL_COLOR_HEX (0x667085)
#endif

void page_metric_bp_detail_layout_build(
    lv_obj_t *parent, const health_ui_bp_metric_detail_data_t *data);

#endif
